name: PeterdeGuzman
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v3
            - name: install packages
              run: make install
            - name: format
              run: make format
            - name: lint
              run: make lint
            - name: test
              run: make test
